name: Deployment

concurrency: production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Заполнение переменных среды"
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "ENVIRONMENT=${{ vars.ENVIRONMENT }}" >> .env
          echo "USE_WEBHOOK=${{ vars.USE_WEBHOOK }}" >> .env
          echo "BOT_NAME=${{ vars.BOT_NAME }}" >> .env
          echo "ADMIN_USER_ID=${{ vars.ADMIN_USER_ID }}" >> .env

      - name: "Создадим каталог проекта"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /home/user/altyysha.com

      - name: "Скопируйте .env в папку проекта."
        run: mv .env ./bot || ls ./bot

      - name: "Скопируйте файлы приложения на удаленный сервер."
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "/var/www/altyysha.com"

  publish:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: "Создадим веб-сеть и запустите docker compose."
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/altyysha.com/
            docker compose up -d
            docker compose ps

      - name:  "Переключим бота с Pulling на Webhook."
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/altyysha.com/
            docker compose exec altyysha php /var/www/html/init_webhook.php

  test-web:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: "Проверка доступности сайта"
        uses: wei/curl@v1
        with:
          args:  https://altyysha.com/

  test-bot:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: "Проверка доступности бота"
        uses: wei/curl@v1
        with:
          args:  https://altyysha.com/bot_script.php

  alert:
    name: Alert
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}